name: CI pipeline

on:
  push:
    branches:
      - 'features/**'
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:

  lint:
    name: "Linter: tflint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - name: Ejecutando tflint a módulos terraform 
        run: |
          cd iac/modules
          tflint